Dockerfile, README.md
[![linuxserver.io](https://www.linuxserver.io/wp-content/uploads/2015/06/linuxserver_medium.png)][linuxserverurl]
+ adds curl package for app to app communication from scripts etc.
=> add curl package per LT support thread

README.md
[![linuxserver.io](https://www.linuxserver.io/wp-content/uploads/2015/06/linuxserver_medium.png)][linuxserverurl]
+ Add information about securing the webui with a password and username found in #8
=> Readme password

Dockerfile, README.md
+ add p7zip, tar , unrar and unzip packages
=> add p7zip, tar , unrar and unzip packages

Dockerfile, README.md
=> Add rsync package

Dockerfile, README.md
=> use edge repo for transmission

Dockerfile, README.md
+ with edge and 3.8 repos containing the same transmission version easier to rebase now.
=> rebase to alpine 3.8, don't need to pull from edge

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, Jenkinsfile, README.md, jenkins-vars.yml, readme-vars.yml
Reference issues: 
https://github.com/linuxserver/docker-transmission/issues/55
https://github.com/linuxserver/docker-transmission/issues/65
Pull Requests: 
https://github.com/linuxserver/docker-transmission/pull/56
https://github.com/linuxserver/docker-transmission/pull/54
https://github.com/linuxserver/docker-transmission/pull/52
https://github.com/linuxserver/docker-transmission/pull/42
As the codebase has changed since these issues and Pulls were created I put the changes into this one. 
This has been smoke tested with a download loop in all of the optional Web UIs along with default.
=> Rebase to Alpine 3.9, add themes to baseimage, add python and findutil

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml
Adding Kettu - Transmission Web UI.
=> adding Kettu

README.md, readme-vars.yml, root/defaults/blocklist-update.sh, root/defaults/settings.json
Right now anyone using a blocklist has a zombie pid spawning every day.
=> #77 need a sigterm in blocklist to properly close transmission pid

Jenkinsfile, README.md, jenkins-vars.yml, readme-vars.yml
Once this is merged, we need to update the trigger on jenkins to check 3.10 repo as well.
=> update package label to match 3.10 repo

Jenkinsfile, README.md, jenkins-vars.yml, readme-vars.yml
=> update auth info in readme, fix version command

readme-vars.yml, root/app/blocklist-update.sh, root/etc/cont-init.d/20-config
Opening this to keep track of discussion.
=> Use transmission-remote to update blocklist

README.md, readme-vars.yml, root/etc/cont-init.d/20-config
=> remove unnecessary chmod

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf
We welcome all PR’s though this doesn’t guarantee it will be accepted.
This commit updates the Alpine version to 12 and the Transmission version to 3.
Updates the Transmission version which brings new features like labels.
I have run the image for the x86_64 architecture.
Fixes #112
=> Update to Alpine 12 and Transmission 3

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, Jenkinsfile, jenkins-vars.yml
=> Update version tag, pin app version

root/etc/cont-init.d/20-config
…ssword to empty string.
Add opportunity to disable authentification by setting USER and PASSWORD to empty string.
After we use at least once USER and PASSWORD with values and enabled authentificxation, we can not disable it. This PR made this possible
Yes
=> Add opportunity to disable authentification

README.md, readme-vars.yml, root/defaults/settings.json, root/etc/cont-init.d/20-config
add support for rpc-host-whitelist notation and WHITELIST env var
* Add support for rpc-host-whitelist notation by providing default values in settings.json
* Add a variable WHITELIST which give control over rpc-whitelist and rpc-host-whitelist. If WHITELIST is empty, disable whitelist
Yes
=> add support for rpc-host-whitelist notation and WHITELIST env var

.github/workflows/external_trigger.yml, Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, Jenkinsfile, README.md, jenkins-vars.yml, readme-vars.yml
This is part of a larger rebasing effort. Issues are tracked on an internal sheet.
=> rebase to Alpine 3.13

readme-vars.yml, root/etc/cont-init.d/20-config
With PR #141  was introduced a typo bug when whitelist are involved
And it appears that we need to control whitelist and host-whitelist separatly to cover all needed control on whitelist types (ip list AND dns named)
Have 2 variable WHITELIST and HOST_WHITELIST to have independent control on whitelit and host-whitelist
This PR also fix #148
=> Split whitelist and host-whitelist separated in two env vars

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml
I'm the creator of Flood for Transmission. And I was hoping that you would be willing to include this alternative UI as an option in your build. Hence why I decided to create a PR.
Flood for Transmission is feature complete and has all the features the default Transmission UI does. I noticed there is already other alternative UI's so I don't think it is too much of stretch from your usual UI.
Do feel free to check out the UI here: https://github.com/johman10/flood-for-transmission/tree/master/screenshots#readme.
I also figured to properly …
=> Add flood-for-transmission as an alternative UI

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml
Closes #183 
Styling change and Alpine 3.15 no longer builds unrar need to compile from source.
=> rebase to 3.15 include #183 symlink changes

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, readme-vars.yml
Add [Transmissionic](https://github.com/6c65726f79/Transmissionic) as an UI option.
The actively maintained and modern web UI Transmissionic is an alternative UI to the existing and already proposed UIs.
Providing a new UI option that is well maintained and multilingual is an advantage for people looking for a simple way to control Transmission Daemon.
Build done with an Azure DevOps pipeline and deployed on AMD64 architecture.
None
=> Add Transmissionic as a UI option.

root/etc/s6-overlay/s6-rc.d/init-transmission-config/run
=> Only chown download and watch folders if permissions are wrong

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, root/etc/s6-overlay/s6-rc.d/init-transmission-config/run
=> Split permissions checks to avoid missing folders

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, readme-vars.yml
Alpine removed transmission-remote from the main transmission meta-package.
Closes #243
=> Explicitly install transmission-remote.

Dockerfile, Dockerfile.aarch64, README.md, readme-vars.yml, root/etc/s6-overlay/s6-rc.d/svc-transmission/run
Closes #250 
Won't build until Alpine fix their arm building issue.
=> Allow custom ports for readiness check, bump unrar to 6.8.2, add transmission-extra

Dockerfile, Dockerfile.aarch64, Jenkinsfile, README.md, jenkins-vars.yml, readme-vars.yml
=> Print version on init
